// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package bar

import (
	"net/http"
)

type CreateOrderOrderUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateOrderOrderUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateOrderOrderUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateOrderOrderUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

type CreateOrderOrderUpdateRequestBody struct {
	// An order for a drink or ingredient.
	Order *OrderInput `json:"order,omitempty"`
}

func (o *CreateOrderOrderUpdateRequestBody) GetOrder() *OrderInput {
	if o == nil {
		return nil
	}
	return o.Order
}

type CreateOrderRequest struct {
	RequestBody []OrderInput `request:"mediaType=application/json"`
	// The url to call when the order is updated.
	CallbackURL *string `queryParam:"style=form,explode=true,name=callback_url"`
}

func (o *CreateOrderRequest) GetRequestBody() []OrderInput {
	if o == nil {
		return []OrderInput{}
	}
	return o.RequestBody
}

func (o *CreateOrderRequest) GetCallbackURL() *string {
	if o == nil {
		return nil
	}
	return o.CallbackURL
}

type CreateOrderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The order was created successfully.
	Order *Order
}

func (o *CreateOrderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateOrderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateOrderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateOrderResponse) GetOrder() *Order {
	if o == nil {
		return nil
	}
	return o.Order
}
