// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package bar

import (
	"net/http"
)

type GetDrinkRequest struct {
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (o *GetDrinkRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

type GetDrinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A drink.
	Drink *Drink
}

func (o *GetDrinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetDrinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetDrinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetDrinkResponse) GetDrink() *Drink {
	if o == nil {
		return nil
	}
	return o.Drink
}
