// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package bar

import (
	"net/http"
)

var ListDrinksOpServerList = []string{
	"https://speakeasy.bar",
	"https://test.speakeasy.bar",
}

type ListDrinksRequest struct {
	// The type of drink to filter by. If not provided all drinks will be returned.
	DrinkType *DrinkType `queryParam:"style=form,explode=true,name=drinkType"`
}

func (o *ListDrinksRequest) GetDrinkType() *DrinkType {
	if o == nil {
		return nil
	}
	return o.DrinkType
}

type ListDrinksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A list of drinks.
	Classes []Drink
}

func (o *ListDrinksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDrinksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDrinksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListDrinksResponse) GetClasses() []Drink {
	if o == nil {
		return nil
	}
	return o.Classes
}
