// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package bar

import (
	"errors"
	"github.com/speakeasy-sdks/bar/internal/utils"
)

var ErrUnsupportedOption = errors.New("unsupported option")

const (
	SupportedOptionServerURL            = "serverURL"
	SupportedOptionRetries              = "retries"
	SupportedOptionAcceptHeaderOverride = "acceptHeaderOverride"
)

type Options struct {
	ServerURL *string
	Retries   *utils.RetryConfig
}

type Option func(*Options, ...string) error

// WithMethodServerURL allows providing an alternative server URL.
func WithMethodServerURL(serverURL string) Option {
	return func(opts *Options, supportedOptions ...string) error {
		if !utils.Contains(supportedOptions, SupportedOptionServerURL) {
			return ErrUnsupportedOption
		}

		opts.ServerURL = &serverURL
		return nil
	}
}

// WithMethodTemplatedServerURL allows providing an alternative server URL with templated parameters.
func WithMethodTemplatedServerURL(serverURL string, params map[string]string) Option {
	return func(opts *Options, supportedOptions ...string) error {
		if !utils.Contains(supportedOptions, SupportedOptionServerURL) {
			return ErrUnsupportedOption
		}

		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		opts.ServerURL = &serverURL
		return nil
	}
}

// WithRetries allows customizing the default retry configuration.
func WithRetries(config utils.RetryConfig) Option {
	return func(opts *Options, supportedOptions ...string) error {
		if !utils.Contains(supportedOptions, SupportedOptionRetries) {
			return ErrUnsupportedOption
		}

		opts.Retries = &config
		return nil
	}
}
