// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package bar

import (
	"net/http"
)

type StockUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// An unknown error occurred interacting with the API.
	Error *Error
}

func (o *StockUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StockUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StockUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *StockUpdateResponse) GetError() *Error {
	if o == nil {
		return nil
	}
	return o.Error
}

type StockUpdateRequestBody struct {
	Drink      *DrinkInput      `json:"drink,omitempty"`
	Ingredient *IngredientInput `json:"ingredient,omitempty"`
}

func (o *StockUpdateRequestBody) GetDrink() *DrinkInput {
	if o == nil {
		return nil
	}
	return o.Drink
}

func (o *StockUpdateRequestBody) GetIngredient() *IngredientInput {
	if o == nil {
		return nil
	}
	return o.Ingredient
}
