// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bar-go/models/components"
	"net/http"
)

type CreateOrderRequest struct {
	RequestBody []components.OrderInput `request:"mediaType=application/json"`
	// The url to call when the order is updated.
	CallbackURL *string `queryParam:"style=form,explode=true,name=callback_url"`
}

func (o *CreateOrderRequest) GetRequestBody() []components.OrderInput {
	if o == nil {
		return []components.OrderInput{}
	}
	return o.RequestBody
}

func (o *CreateOrderRequest) GetCallbackURL() *string {
	if o == nil {
		return nil
	}
	return o.CallbackURL
}

type CreateOrderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The order was created successfully.
	Order *components.Order
}

func (o *CreateOrderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateOrderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateOrderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateOrderResponse) GetOrder() *components.Order {
	if o == nil {
		return nil
	}
	return o.Order
}
