// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// APIError - An error occurred interacting with the API.
type APIError struct {
	Code    *string                `json:"code,omitempty"`
	Message *string                `json:"message,omitempty"`
	Details map[string]interface{} `json:"details,omitempty"`
}

var _ error = &APIError{}

func (e *APIError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
